name = "GRAPE"
uuid = "6b52fcaf-80fe-489a-93e9-9f92080510be"
authors = ["Alastair <alastair@nvision-imaging.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
