name = "GRAPE"
uuid = "6b52fcaf-80fe-489a-93e9-9f92080510be"
authors = ["Michael Goerz <mail@michaelgoerz.net>"]
version = "0.7.6"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LBFGSB = "5be7bae1-8223-5378-bac3-9e7378a2f6e6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuantumControl = "8a270532-f23f-47a8-83a9-b33d10cad486"
QuantumGradientGenerators = "a563f35e-61db-434d-8c01-8b9e3ccdfd85"

[weakdeps]
Optim = "429524aa-4258-5aef-a3af-852621145aeb"


[extensions]
GRAPEOptimExt = "Optim"
# GRAPELBFGSBExt = "LBFGSB"
# Cannot load GRAPELBFGSBExt as an extension if LBFGSB is a hard
# dependency. See `include` in `src/GRAPE.jl`.

[compat]
Dates = "1"
LBFGSB = "0.4"
LinearAlgebra = "1"
Optim = "1"
Printf = "1"
QuantumControl = "0.11.1"
QuantumGradientGenerators = "0.1.8"
julia = "1.9"
