version = 1

[[annotations]]
path = "CLAUDE.md"
SPDX-FileCopyrightText = "© 2025 Michael Goerz <mail@michaelgoerz.net>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "docs/src/inventories/*"
SPDX-FileCopyrightText = "© 2025 Michael Goerz <mail@michaelgoerz.net>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "paper/paper.bib",
    "docs/src/refs.bib"
]
SPDX-FileCopyrightText = "© 2025 Michael Goerz <mail@michaelgoerz.net>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    ".github/workflows/*.yml",
    ".github/*.yml",
]
SPDX-FileCopyrightText = "© 2025 Michael Goerz <mail@michaelgoerz.net>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "**/Project.toml",
    "**/Manifest.toml",
]
SPDX-FileCopyrightText = "© 2025 Michael Goerz <mail@michaelgoerz.net>"
SPDX-License-Identifier = "CC0-1.0"
